name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - main

permissions:
  id-token: write      # Required for OIDC
  contents: read       # Required to checkout code

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::656697807925:role/GitHubOIDCRole-aws-terraform-explore
          aws-region: ap-southeast-7
          audience: sts.amazonaws.com

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./aws-terraform-explore

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./aws-terraform-explore

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./aws-terraform-explore
        
      # --- Application Deployment Steps (kubectl) ---
  
      - name: Configure kubectl
        run: $(terraform output -raw configure_kubectl)
  
      - name: Deploy Application to EKS
        run: kubectl apply -f kubernetes/deployment.yaml
